apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus-app-4"
  annotations:
    argocd/app-name: my-quarkus-app-4-dev
    backstage.io/kubernetes-id: my-quarkus-app-4
    github.com/project-slug: janus-demo-video/my-quarkus-app-4
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-96gs6.96gs6.sandbox2905.opentlc.com/#https://github.com/janus-demo-video/my-quarkus-app-4?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-96gs6.96gs6.sandbox2905.opentlc.com/#https://github.com/janus-demo-video/my-quarkus-app-4?che-editor=che-incubator/che-idea/next&devfilePath=.devfile-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "mattheh"